### ISSUE TITLE
Portfolio review for Michael

### ISSUE THREAD

**Issue by evilb4k4** [portermichael/portfolio#15]
Overall your portfolio is functional and look great. The only suggestion i would give is add more about yourself like images, and some more interactions ( maybe more transition like when you open the read on the way they bounce is cool. )for the user to help them learn more about you as a developer. On your code I'm not sure why you have 2 style folder with the same module.css if you can just combined them or delete one of them other than that i don't see and other unnecessary code.

**Comment by portermichael** [comment]
Thanks for the feedback Adan. It looks like the folders were duplicated accidentally. I've removed them and will add more flavor to the app.
